### ISSUE TITLE
JOSS Review: Dependency Managment 

### ISSUE THREAD

**Issue by elimillera** [RoryChenXY/DataRepExp_public#2]
From the JOSS Guidelines:

>  Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

There does not appear to be a list of packages and their versions. The app.R file does contain the libraries that are loading in, and as of today I have no issues installing and loading the packages, however this may not be the case when updates occur to dependencies.

For a project like this I would recommend using {renv} to manage the dependencies of the application. This will create a machine-readable JSON file where environment state can be saved and restored for better reproducibility: https://rstudio.github.io/renv/articles/renv.html

**Comment by RoryChenXY** [comment]
@elimillera, thank you for your input.
I have utilised {renv} as suggested, as well as the DESCRIPTION file and NAMESPACE for dependency management

**Comment by RoryChenXY** [comment]
I think all issues here are resolved
