### ISSUE TITLE
JOSS Review: Documentation 

### ISSUE THREAD

**Issue by elimillera** [RoryChenXY/DataRepExp_public#3]
From the JOSS Guidelines:

>  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

I would suggest adding how this could be used for non-simulated data and documentation of how this data should be structured. I'm not familiar with FAIR data so I'm not sure if the 'simdata.RData' is standard, but a note for how this Rdata file should be structured or a helper function that does the load from disk, would help a user know how to use their own data.

**Comment by RoryChenXY** [comment]
The 'simdata.RData' is not standard.

Basically, the app requires 3 data frames: study-level data, participant-level data and a data dictionary.
It still requires some 'hard coding' to get the user data ready and modify the app for their own purposes.

We have two data repository partners who are interested in this app, I will work with them to build a better documentation.
